kind: Service
apiVersion: v1
metadata:
  name: prometheus-service
  labels:
    app: prometheus-server
spec:
  selector:
    app: prometheus-server
  ports:
    - port: 8080
      targetPort: 9090
      protocol: TCP
      nodePort: 30000
  type: NodePort
