---

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-config-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: models-1-0-0